### ISSUE TITLE
handler_shiny showing detail but not message

### ISSUE THREAD

**Issue by FedericoTrifoglio** [HenrikBengtsson/progressr#109]
`handler_shiny()` only shows `detail` and not `message`. I've removed `message = state$message` from the `reporter` and it shows both.

This below shows both `detail` and `message`
```
library(shiny)
library(progressr)
shiny_handler <- make_progression_handler("shiny", reporter = list(
  update = function(config, state, progression, ...) {
    shiny::incProgress(progression$amount / config$max_steps)
  }
), target = "gui")
shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot({
      X <- 1:15
      withProgressShiny(message = "Calculation in progress",
                        detail = "This may take a while ...", value = 0, {
                          p <- progressor(along = X)
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p()
                          })
                        }, handlers = shiny_handler)
      plot(cars)
  })
}
)
```

This only shows `message`

```
library(shiny)
library(progressr)
shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot({
      X <- 1:15
      withProgressShiny(message = "Calculation in progress",
                        detail = "This may take a while ...", value = 0, {
                          p <- progressor(along = X)
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p()
                          })
                        }, handlers = handler_shiny)
      plot(cars)
  })
}
)
```

**Comment by HenrikBengtsson** [comment]
Thanks for reporting on this and for providing reproducible examples to work with - really helps.

I agree that the current behavior is less than ideal.  There are a few things that can be improved and also a few things that need to be figured out.

First, the `withProgressShiny(message = ...)` does actually end up being displayed, but it's immediately erased when you create the `progressor()`.  You can actually set a "sticky" message in the `progressor()` call.  The following illustrates both:

```r
library(shiny)
library(progressr)
handlers("shiny")

app <- shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot({
      X <- 1:15
      withProgressShiny(message = "Calculation in progress",
                        detail = "This may take a while ...", value = 0, {
                          Sys.sleep(2.0)
                          p <- progressor(along = X, message = "Yeah, calculation in progress")
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p()
                          })
                        })
      plot(cars)
  })
}
)

print(app)
```

What can be improved is to:

* [ ] have `progressor()` automatically inherit argument `message` of `withProgressShiny()`, because that might be expected by the developer when moving from `shiny::withProgress()` to `progressr::withProgressShiny()`.

Second, you can also update the "message" in every single "tick", i.e. when calling `p()` above, as in:

```r
      withProgressShiny(message = "Calculation in progress",
                        detail = "This may take a while ...", value = 0, {
                          p <- progressor(along = X)
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p(sprintf("Processing x=%d", x))
                          })
                        })
```

This brings me to another open question, which has been on my todo list to look into; 

* [ ] should `progressor(..., message=...)` and `p("a message")` update the 'message' or the 'detail' component of the Shiny progress panel?

How are people doing it now?  Is there a de facto standard for this?  Personally, I'm leaning to it should be the 'detail' info that should be updated in each iteration and the 'message' should be used more as a 'title'.

**Comment by FedericoTrifoglio** [comment]
Based on this https://shiny.rstudio.com/articles/progress.html, I expect most people (myself included) would want the "detail" component to update at every iteration, while the message stays fixed. Also because of the way the two are formatted (message = bold vs detail = regular), I feel `progressor()` should inherit `detail` by default so it can be updated with `p(sprintf("Processing x=%d", x))`.

Sorry but I'm not sure what you mean to ask with the third question. 

I'll use this output, as an example.

```
Step 5
Step 10
  |====================                               |  43%
```

Do you mean should the output generated by `p(sprintf("Step %d", kk), class = if (kk %% 5 == 0) "sticky", amount = 0)` be "message" and the one generated by `p(message = sprintf("Added %g", x[kk]))` be "detail"?

I personally think both should be "detail" and "message" stays always fixed.

**Comment by HenrikBengtsson** [comment]
Thanks for that pointer. That helps.  Yes, that's what I meant by the "sticky" messages.

Maybe one could give full control to the developer by introducing am optional, special markup for the `message` and `detail` arguments

```r
withProgressShiny(message = "Processing files", detail = "{{progressr::message}}", {
  ...
  p("This message will update 'detail'")  
  p("This message will end up in the void", class = "sticky")
})
```

and

```r
withProgressShiny(message = "{{progressr::sticky-message}}", detail = "{{progressr::message}}", {
  p("This message will update 'detail'")  
  p("This message will update 'message'", class = "sticky")  
})
```

If none are used, they're never updated;

```r
withProgressShiny(message = "A fixed message", detail = "Contstant details", {
  p("This message will end up in the void")
  p("This message will end up in the void", class = "sticky")
})
```

**Comment by HenrikBengtsson** [comment]
I've updated the 'develop' branch so that:

1. The new default for `withProgressShiny()` and `handler_shiny()` is to have progression messages update the 'detail' component of Shiny progress panels.  Previously it was the 'message' component.

2. This can be fully controlled via a new argument `inputs`. One can also control what sticky progression messages updates.

For example, here is how to get the old behavior back:

```r
library(shiny)
library(progressr)

app <- shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot({
      X <- 1:20
      withProgressShiny(message = "Processing files", # default 'message'
                        detail = "Starting ...",      # default 'detail'
                        # New default
                        # inputs = list(message = NULL, detail = "message"),
                        # Old default
                        inputs = list(message = "message", detail = NULL),
                        value = 0, {
                        Sys.sleep(3)
                          p <- progressor(along = X)
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p(sprintf("x=%d", x))
                          })
                        })
      plot(cars)
  })
}
)

runApp(app)
```
