### ISSUE TITLE
Customized signal fired twice

### ISSUE THREAD

**Issue by dipterix** [HenrikBengtsson/progressr#68]
Thanks for the great idea. I tried to send arbitrary R objects through the framework in condition. I found my customized handlers fire signals twice in `future()`. Here is my code:

```r
# Function returning condition with classes: 'immediateCondition', 'progression'
immediate_condition <- function(message, call = NULL, ...){
  structure(list(message = message, call = call, ...), 
            class = c('immediateCondition', 'progression', 'condition'))
}

# Register customized handler
progressr::handlers(
  dipsaus = function(interval = getOption("progressr.interval", 0),
                     intrusiveness = getOption("progressr.intrusiveness.auditory", 
                                               5),
                     ...) {
    reporter <- local({
      list(
        dipsaus = function(...) {
          print(list(...)[['message']])
        }
      )
    })
    progressr::make_progression_handler(
      "dipsaus",
      reporter,
      handler = function(cond) {
        f <- reporter[[cond$type]]
        if (is.function(f)) {
          do.call(f, cond)
        }
      },
      intrusiveness = intrusiveness,
      ...
    )
  }
)

# Modified summation
# Define function
slow_sum <- function(x, f = lapply) {
  y <- f(1:10, function(x, ...) {
    cond <- immediate_condition(x, type = 'dipsaus')
    withRestarts(signalCondition(cond), muffleProgression = function(p) NULL)
    Sys.sleep(0.1)
    sqrt(x)
  })
  invisible()
}
```

Here's the result running in single session:
```r
progressr::with_progress({
  slow_sum(1:10)
})
```

```
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
```

Here's result using `future_lapply`:

```r
future::plan(future::multisession, workers = 3)
progressr::with_progress({
  slow_sum(1:10, future.apply::future_lapply)
  print('finished')
})
```

```
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 1
[1] 2
[1] 3
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] "finished"
```

**Comment by HenrikBengtsson** [comment]
This is due to a bug in `future::values()`, which future.apply relies on.  The bug is fixed in the [develop version of future](https://github.com/HenrikBengtsson/future/tree/develop);

```
BUG FIXES:

 * values() would resignal immediateCondition:s despite those should only be
   signalled at most once per future.
```

**Comment by dipterix** [comment]
Thanks. I just installed develop version. This time it's not firing twice, but the order seems weird. Not sure if it's normal.

If I use `future::plan(future::multicore)`, the result will be `1-10` sequentially, but if I use `future::plan(future::multicore, workers = 3)`, the result is `4-10`, then `1-3`.

```
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 1
[1] 2
[1] 3
[1] "finished"
```

Also is my handler function created in the way as it's supposed to? Since there's no instructions, I just followed your progression functions. In order for handlers to receive the signal, the condition must inherit both `immediateCondition` and `progression`. Is there a simpler way to fire signals from within `future` only inherit `immediateCondition` and can be received by handlers?

Thanks.

**Comment by HenrikBengtsson** [comment]
> If I use `future::plan(future::multicore)`, the result will be `1-10` sequentially, but if I use `future::plan(future::multicore, workers = 3)`, the result is `4-10`, then `1-3`.

Three things: 

First, `future_apply(X)` will process the elements on `X` via `n=nbrOfWorkers()` [here n=3] chunks, where each chunk is resolved by one future.  Each future is resolved by one worker. For example,
```r
> library(future.apply)
> plan(multisession, workers=3)
> y <- future_lapply(1:10, function(ii) Sys.getpid())
> str(y)
List of 10
 $ : int 24460
 $ : int 24460
 $ : int 24460
 $ : int 24510
 $ : int 24510
 $ : int 24510
 $ : int 24510
 $ : int 24560
 $ : int 24560
 $ : int 24560
```
As you see, first chunk processes elements 1:3, second 4:7, and third 8:10.

Second, your immediateCondition:s are relayed in the main R process only when the future is resolved and the results are retrieved by the main process.  So, for the first chunk you'll signal 3 immediateCondition:s, which are gathered by the future and then resignaled all at once.  Same for the second and third chunk.  This explains why they are sequentially grouped within each chunk.  If you wonder about near-live signaling, see Issue #66.

Third, since the relaying/resignalling happens as soon as a future is done, and you're doing parallel processing, you have no control of the order in which the futures (=chunks) complete.  Thus, you should expect out-of-order signaling of the chunks.  Now, will near-live signaling (Issue #66), you'd might even get interweaved out-of-order signaling.  Again, expected per design.  This is only happening for immediateCondition.  Other conditions (and stdout) will be gathered in order by the future framework and relayed in order at the end.

> Also is my handler function created in the way as it's supposed to? Since there's no instructions, I just followed your progression functions. In order for handlers to receive the signal, the condition must inherit both `immediateCondition` and `progression`. Is there a simpler way to fire signals from within `future` only inherit `immediateCondition` and can be received by handlers?

It looks like you've got it right.  No documentation on this part yet because, other than lack of time, it might change as progressr matures and more devs like you try it out and give feedback like this.  So, for now, the source code is the docs when it comes to the internals.

I did indeed notice that there might be a lower-level framework growing out of the progressr framework.  I decided to have progressr mature first while keeping such a more-generic framework in mind.  So, it's not unlikely that something more generic will come out of this.

**Comment by dipterix** [comment]
Thanks. This sounds great. Do you have any plans to make it on CRAN in the near future?

**Comment by HenrikBengtsson** [comment]
I do.  The last of two "blocking" downstream packages hit CRAN today, which will allow me to start preparing the next release of _future_ (involves revdep checks, validation on tons of platforms and R version, ...).  So, you can expect something soon.

If your question was about release progressr on CRAN, then the answer is not yet - I'm rather conservative when it comes to release the first version (don't want to break things for others later).  It API needs more work, which comes from more real-world exposure.

**Comment by HenrikBengtsson** [comment]
Went fairly quick; [future](https://cran.r-project.org/web/packages/future) 1.15.0 just hit CRAN
