### ISSUE TITLE
Add messages above the progress bar

### ISSUE THREAD

**Issue by hongyuanjia** [HenrikBengtsson/progressr#75]
Thanks for this amazing package. Right now I am trying to adopting from [progress](https://github.com/r-lib/progress) package to progressr, in order to better handle integration with the future framework.

The progress package has a useful functionality to [print custom messages](https://github.com/r-lib/progress/blob/b146a6a74d14c1cf4a3689ae745a0c0f38a355d2/R/progress.R#L54) above the progress bar. My package [leans heavily on this](https://github.com/hongyuanjia/eplusr/blob/9717b7515bec99451abc6b11a5bd54594852620d/R/run.R#L584) to give the user some informative messages on what's going on during the calculations. I am wondering if progressr has this kind of functionality?

Thanks!

**Comment by HenrikBengtsson** [comment]
For my own notes, this feature request is for something like:
```r
library(progress)
my_fcn <- function() {
  pb <- progress_bar$new(total = 100)
  for (i in 1:100) {
    pb$tick()
    if (i %% 10 == 0) pb$message(sprintf("Step #%d done", i))
    Sys.sleep(1 / 100)
  }
}
```
which outputs:
```r
> my_fcn()
Step #10 done
Step #20 done
Step #30 done
Step #40 done
[===================>--------------------------------]  46%
```

The `progress_bar$message(s)` function resets the line and outputs `s` with a newline and then renders the progress bar itself.

**Comment by HenrikBengtsson** [comment]
Although there's probably a fairly quick, technical solution for the **progress** handler, this requires taking a step or two back to see if there is a more general design so that this extra info may also make sense for other handlers.  There needs to be a way to specify these "extra" messages in the progression function.  Just recording my thoughts here until I have time to return to this:

With
```r
 p <- progressr::progressor(along = x)
```
this can be done by for instance having a separate argument for these "extra" messages:
```r
p(message = sprintf("Added %g", x[i]), sticky_message = if (i %% 10 == 0) sprintf("Step #%d", i))
```
or by reusing the existing `message` argument by marking it as "sticky":
```r
p(message = sprintf("Added %g", x[i]), sticky = (i %% 10 == 0))
```
Another flavor, or an internal representation, of the latter could be to pass the "sticky" info as a class attribute of the `message` itself, e.g.
```r
p(message = structure(sprintf("Added %g", x[i]), class = if (i %% 10 == 0) "sticky_message"))
```
This design would only require that the **progressr** framework/protocol preserves the class attribute of the `message` so that it's available to the handler.  Then the handler can do whatever it want if it, e.g. support it or ignore it.  The `handler_progress()` handler can call `progress_bar$message(...)` on it.  An auditory text-to-speech handler can read out the message in a different style, pitch, or in other ways emphasize it.

**Comment by HenrikBengtsson** [comment]
Spend a few more brain cycles to think about this one.  I wonder if the reason for the existence of the `progress_bar$message()` method as in:
```r
pb$message(sprintf("Step #%d done", i))
```
is _simply_ because we cannot use a good-old `message(sprintf("Step #%d done", i))` call, because that will result in cluttered output.  For example, with:
```r
library(progress)
my_fcn <- function() {
  pb <- progress_bar$new(total = 100)
  for (i in 1:100) {
    pb$tick()
    if (i %% 10 == 0) message(sprintf("Step #%d done", i))
    Sys.sleep(1 / 100)
  }
}
```
we get:
```r
> my_fcn()
Step #10 done
[==========>------------------------------------------]  20%Step #20 done
[===============>-------------------------------------]  30%Step #30 done
[====================>--------------------------------]  40%Step #40 done
[=========================>---------------------------]  50%Step #50 done
[===============================>---------------------]  60%Step #60 done
[====================================>----------------]  70%Step #70 done
[=========================================>-----------]  80%Step #80 done
[===============================================>-----]  90%Step #90 done
Step #100 done 
```

Now, _if_ we could figure out a way for `message()` and `progress_bar$tick()` to play nicely with each other, then there is no need for handling this specially in the progressor function `p()`.  

Being able to make use of a simple `message()`, `cat()`, and `print()` call is much more natural.  It will also then also work out of the box with other functions outputting to the terminal, which there are lots of "out there".

**Comment by HenrikBengtsson** [comment]
Solved it!

You can now use regular R functions such as `message()`, `cat()`, `print()`, etc. to output "above" the progress bar.  For example, with:

```r
my_fcn <- function() {
  p <- progressor(100L)
  for (i in 1:100) {
    p()
    if (i %% 10 == 0) message(sprintf("Step #%d done", i))
    Sys.sleep(1 / 100)
  }
}
```

you'll get:

```r
> library(progressr)
> handlers("progress")
> with_progress(my_fcn())
Step #10 done
Step #20 done
Step #30 done
[=========>------------------]  36%
```

which I think is what you want.  Note how natural this is, because it is completely orthogonal to whether you use progress output or not.

This is available in the 'develop' branch and will be part of the next release.


\<patting myself on the shoulder\>
This is actually pretty neat and extremely useful. There are lots of functions out there that produce output and, as developers, we are often not in control of such output, which means they would interfere with out progress bars in the terminal.
\</patting myself on the shoulder\>

**Comment by HenrikBengtsson** [comment]
Forgot to say, I'm aware that there still might be a need to sticky messages that only take place when reporting on progress.  So, I'll keep this issue open for that.

**Comment by HenrikBengtsson** [comment]
I've now also added support for "sticky" _progress_ messages, e.g.
```r
my_fcn <- function() {
  p <- progressor(100L)
  for (i in 1:100) {
    if (i %% 10 == 0) p(sprintf("Step #%d done", i), amount = 0, class = "sticky")
    p(sprintf("Processing %d", i))
    Sys.sleep(1 / 100)
  }
}
```
which gives:

```r
> handlers("progress")
> with_progress(y <- my_fcn())
Step #10 done                                                     
Step #20 done                                                     
Step #30 done                                                     
Step #40 done                                                     
Step #50 done                                                     
Step #60 done                                                     
Step #70 done                                                     
[=================================>-----------]  76% Processing 76
```
