### ISSUE TITLE
progress not reported from Rscript

### ISSUE THREAD

**Issue by jeffzi** [HenrikBengtsson/progressr#77]
Hi,

Thanks for the package. I tried to execute a simple example with Rscript but progress is not reported. I could not find mentions of Rscript in the documentation or issues. Maybe I missed something obvious?

``` r
library(progressr)

handlers("txtprogressbar", "beepr")

with_progress({
  pb <- progressor(steps = 10)
  for (i in 1:10) {
    pb()
    Sys.sleep(1/10)
  }
})
```

**Comment by HenrikBengtsson** [comment]
This is a due to a conservative design decision.  It was based on not cluttering up log files with progress bar information (which doesn't render well on file) when running in non-interactive mode.  Another reason is that is common to run many R scripts in batch mode at the same time, e.g. batch processing of many data sets in parallel.  In that case, especially auditory output like 'handlers(beepr)' will be very annoying.  This is why the default is silence those in non-interactive mode.

For now, you need to set `with_progress(..., enable=TRUE)` to enable progress updates in non-interactive mode.  Another approach is to enable it for each handler separately, e.g.

```r
handlers(list(
  handler_txtprogressbar(enable = TRUE), 
  handler_beepr()
))
```
The above would keep the 'beepr' handler silences in non-interactive mode but running the same script interactive will produce the sound.

Now, another thing that is controlled by interactive/non-interactive mode (=`interactive()`) is whether standard output and conditions such as messages and warnings should be buffered or let through instantly.   When you have a visual progress bar you don't want `print()` and `message()` statements to interweaving the progress bar being rendered.  Because of this, stdout and conditions are captured in interactive mode but not in batch mode.   So, if your function output messages etc, you also need to set:

```r
with_progress({
   ...
}, enable = TRUE, delay_stdout=TRUE, delay_conditions="condition")
```

for things to look nice in also batch mode.   Proof of concept:

```sh
 $ Rscript -e "library(progressr)" -e "with_progress(slow_sum(1:10), delay_stdout=TRUE, delay_conditions='condition', enable=TRUE)"
  |===========                           |  30%
```

PS. I'll add it to the list to see if it is possible to control the above with a single argument.

**Comment by jeffzi** [comment]
Thanks for your explanation. It does work on my side. I suggest to include a remark in the documentation in case other users would face the same issue.

I agree that progress bars don't look nice in a log file. For a command-line program, there are multiple solutions to not clutter the terminal/file:

- Use a logging package, such as [lgr](https://github.com/s-fleck/lgr) to direct logs both into a file and to the terminal. Printing messages is not very robust for logging purposes.
- Accept an argument to choose the level of verbosity. If you run multiple scripts at the same time, you probably want to see warnings and errors but not info messages.

**Comment by HenrikBengtsson** [comment]
FYI, in the next release (develop branch) `with_progress()` will automatically infer whether it needs to buffer ("delay") terminal output or not depending on what progress handlers are set.  This means that:

```sh
$ Rscript -e "library(progressr)" -e "with_progress(slow_sum(1:10), enable=TRUE)"
 |===========                           |  30%
```

will be enough.

BTW, instead of setting `enable = TRUE` in every call, you can override the default by setting option `progressr.enable`;

```sh
$ Rscript -e "library(progressr)" -e "options(progressr.enable=TRUE)" -e "with_progress(slow_sum(1:10))"
 |===========                           |  30%
```

That one works also with the current release version.  If created #79 so that we'll also be able to do:

```
$ R_PROGRESSR_ENABLE=TRUE Rscript -e "library(progressr)" -e "with_progress(slow_sum(1:10))"
```

**Comment by HenrikBengtsson** [comment]
```sh
$ export R_PROGRESSR_ENABLE=TRUE
$ Rscript -e "library(progressr)" -e "with_progress(y <- slow_sum(1:10))"
```
now works.  This has been documented in `?with_progress`, in the package vignette and also the README (here on GitHub).

Thanks for bringing this up.

**Comment by HenrikBengtsson** [comment]
progressr 0.6.0 on CRAN just now.
