### ISSUE TITLE
output bar to stdout not stderr

### ISSUE THREAD

**Issue by joeHickson** [HenrikBengtsson/progressr#96]
Hi,
Is there an easy way to write to stdout not stderr? I'm struggling with output on stderr resulting in the job being marked as failed.

Thanks

Joe

**Comment by HenrikBengtsson** [comment]
Sending progress updates to standard error is by design.  Among other things, it avoids having progress bars ending up in dynamic reports and vignettes.

You can override the default by:

```r
handlers(handler_txtprogressbar(file=stdout()))
```

Having said this, I think the correct solution here is to fix your job script (assuming you're on an HPC scheduler).  There are many things in R that outputs to stderr, e.g. `message()` and `warning()`.   My gut feeling is that, if you cannot disable the "stderr-equals-error" then you can redirect stderr to stdout in the job script as:

```sh
Rscript main.R 2>&1
```

That should covers not only progress bars, but also messages and warnings.

**Comment by joeHickson** [comment]
Redirecting the whole stderr to stdout masks the ability to detect script failures (such as warning()) by monitoring stderr. Thanks for the suggestion of changing the default handler.
